
services:
 mongodb:
    image: mongo:latest
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: uzair
      MONGO_INITDB_ROOT_PASSWORD: uzairyasin123
    volumes:
      - mongo_data:/data/db
    networks:
      - test-network
volumes:
  mongo_data:

networks:
    test-network:
        external: true
